feat: add candidates
YannetGorob/employee_app pull request #4
Opened 2023-03-16 12:51 UTC by YannetGorob

Made the design and model of the list of candidates.

2023-03-16 13:07 UTC, RusKryzhanovskiy requested changes
Приведи структуру проекта к нашей базовой, которую я скинул в чат

2023-03-16 13:07 UTC, RusKryzhanovskiy commented on lib/app/feature/presentation/widgets/candidate_card.dart
> +class CandidatesCard extends StatelessWidget {
1. Candidate (не Candidates), почему - ответишь мне в коментарии
2. CandidateTile более "флатеровский подход" именования такой штуки

2023-03-16 13:07 UTC, RusKryzhanovskiy commented on lib/app/data/models/candidate_model.dart
> +  CandidateModel(this.name, this.surname, this.position, this.image);
Модели по возможности делаем 
1. Named params
2. Const constructor
3. Optional types

Почему лучше для модели сделать String? name; ты мне отпиши в комментарий.

2023-03-16 13:46 UTC, YannetGorob commented on lib/app/feature/presentation/widgets/candidate_card.dart
> +class CandidatesCard extends StatelessWidget {
Потому что карточка на одного кандидата, а не нескольких

2023-03-16 13:50 UTC, YannetGorob commented on lib/app/data/models/candidate_model.dart
> +  CandidateModel(this.name, this.surname, this.position, this.image);
String? name - потому что name может быть null

2023-03-17 08:45 UTC, RusKryzhanovskiy commented on lib/app/data/models/candidate_model.dart
> +  CandidateModel(this.name, this.surname, this.position, this.image);
Потому, что мы обращаемся за данными в интернет. Можем ли мы быть на 100% уверенны в том, что нам всегда прийдет имя?

2023-03-17 08:45 UTC, RusKryzhanovskiy commented on lib/features/candidates/candidates_list/presentation/candidate_tile.dart
> +class CandidateTile extends StatelessWidget {
Между импортами и классом надо энтер

2023-03-17 08:54 UTC, YannetGorob commented on lib/app/data/models/candidate_model.dart
> +  CandidateModel(this.name, this.surname, this.position, this.image);
no

2023-03-17 09:16 UTC, RusKryzhanovskiy approved these changes

2023-03-17 10:04 UTC, merged